-- 1. USE WAREHOUSE, DATABASE, SCHEMA

-- Use warehouse
USE WAREHOUSE COMPUTE_WH;

-- Use database
USE DATABASE INSTACART_DB;

--2. CREATE SCHEMAS (RAW & CURATED)

-- Raw schema (already used by ADF)
CREATE SCHEMA IF NOT EXISTS RAW;

-- Curated schema (for analytics)
CREATE SCHEMA IF NOT EXISTS CURATED;


--3. CHECK RAW TABLES (INGESTED BY ADF)

USE SCHEMA RAW;

SHOW TABLES;



