--. DIMENSION TABLES (CURATED LAYER)

USE SCHEMA CURATED;

--DIM_DEPARTMENTS
CREATE OR REPLACE TABLE DIM_DEPARTMENTS AS
SELECT
    department_id,
    department
FROM RAW.DEPARTMENTS;

--DIM_AISLES
CREATE OR REPLACE TABLE DIM_AISLES AS
SELECT
    aisle_id,
    aisle
FROM RAW.AISLES;

--DIM_PRODUCTS

CREATE OR REPLACE TABLE DIM_PRODUCTS AS
SELECT
    product_id,
    product_name,
    aisle_id,
    department_id
FROM RAW.PRODUCTS;

